class Config:
    CHECK_IF_RUNNING_EVERY_MS = 5000
    RESTART_IF_UNDER_SPEED = 0.03
    LOGIC_FRAME_DURATION_MS = 40
    SEND_CURRENT_SPEED_EVERY_MS = 1000
    SEND_CURRENT_HOUR_EVERY_MS = 10000
    ON_THE_CLOCK_NUM_PERIODS = 20
